// Package swagger provides the Swagger documentation for the Leaderboard Service API.
package swagger

// This file will be auto-generated by swag command

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{"http"},
	Title:       "Leaderboard Service API",
	Description: "API for managing leaderboards, entries, participants, and metrics",
}
